[package]
name = "gba2k"
version = "0.2.0"
edition = "2021"
license = "Zlib OR Apache-2.0 OR MIT"
publish = false

[dependencies]
voladdress = "1"
bitfrob = "0.1.1"
arm7tdmi_aeabi = "0.2"

[profile.dev]
opt-level = 3

[features]
default = ["memory_fns"]
memory_fns = [] # Provides Zlib-only code.
